# Generated by Django 2.0.9 on 2018-12-30 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='maincategory',
            name='icon',
            field=models.FileField(default='category_icons/none/no-img.jpg', upload_to='category_icons/'),
        ),
    ]
