# Generated by Django 2.0.9 on 2019-01-01 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0002_auto_20181230_1821'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='maincategory',
            options={'ordering': ('priority',)},
        ),
        migrations.AddField(
            model_name='card',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='card',
            name='tags',
            field=models.ManyToManyField(blank=True, to='thesaurus.Tag'),
        ),
    ]
