# Generated by Django 2.0.9 on 2019-01-02 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0003_auto_20190101_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='img',
            field=models.ImageField(default='images/card_img/default.ipg', upload_to='images/card_img/'),
        ),
    ]
