# Generated by Django 2.0.9 on 2019-01-03 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('thesaurus', '0005_auto_20190103_2001'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='notes',
            new_name='note',
        ),
        migrations.AlterField(
            model_name='card',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
